// Auto-generated by zitejs generate. Do not edit manually.
//
// Usage in endpoint files (src/api/*.ts):
//   import { zite } from "zitejs/db";
//
// Always use "zitejs/db" — never use relative paths like "../../.zite/db".
// The tsconfig aliases resolve zitejs/* imports to the correct .zite/ files.
//
// Table client methods (all take a single params object):
//   .findAll({ filters?, sort?, offset?, limit?, fields? }) → { records: T[], hasMore: boolean }
//     filters: { fieldName: value } for equality, or { fieldName: { <op>: value } }
//     operators: contains, not, in, notIn, lt, lte, gt, gte
//       `not: null` means "is set". An empty `in: []` matches nothing; an
//       empty `notIn: []` applies no filter.
//     sort is currently IGNORED here — it is stripped before the request.
//       (it does work on zite.auth.findAllUsers). Order in SQL instead.
//     limit defaults to 500, max 2000; offset is a row count (a number)
//     a filter value of `undefined` is REJECTED (it would query unfiltered
//       and match an arbitrary record). Check the value first.
//   .findOne({ id?, filters?, fields? }) → T | undefined
//   .create({ record }) → T
//   .update({ id, record }) → { id: string, fields: Partial<T> }
//   .delete({ id }) → { success: true, id: string }
//   .bulkCreate({ records, matchOn? }) → { success: boolean, records: T[] }
//     up to 100 records per call; matchOn upserts on those fields
//
// Reading these types:
//   SDK names are stable identifiers — they do NOT change when a table or field is
//   renamed. Each carries its current user-facing name in quotes (// "Task Name").
//   Where the two differ the field was renamed, and the quoted name is what it means
//   now — treat it as the source of truth.
//   Values are RAW: dates are ISO strings, durations are seconds. Format them for
//   display yourself, following the display config in each field's comment.
//   PERCENT fields are stored as decimals — 0.5 is 50%, 1.0 is 100%.
//   LINKED RECORD fields hold UUID record ids from findOne/findAll — never invent one.
//   Computed and system-managed fields (formula, rollup, lookup, autonumber,
//   created/updated timestamps and more) are absent from the *Input types —
//   a write to one is rejected or silently dropped.
//
// Zite auth users:
//   zite.auth.findAllUsers({ appIds?, filter?, filters?, sort?, limit?, offset? })
//     Supports the same filter, sort, and pagination options as table .findAll()
//     appIds restricts results to users belonging to any listed app
//   zite.auth.updateUserProfile(userId, { firstName?, lastName?, image? })
//   User email addresses cannot be updated through this API
//
// Raw SQL (read-only SELECTs for aggregates, joins, multi-table queries):
//   zite.sql({ query: "SELECT ...", params?: [...] })
//     → { rows: Record<string, unknown>[], columns, rowCount, truncated }
//     Capped at 2000 rows — `truncated: true` means there were more, so paginate in
//     SQL rather than assuming you got everything. Queries time out after 10s.
//     columns[].name is the SDK name; columns[].originalName is the underlying
//     database column (or your own SQL alias).
//
// SQL guidelines:
//   - Use SDK names for tables (PascalCase) and fields (camelCase)
//   - ALWAYS double-quote every identifier: FROM "Orders", WHERE "status" = $1
//   - Use params array for user input ($1, $2, ...): never interpolate into SQL
//   - Auth users are available as "ziteUsers" with id, name, email, firstName, lastName, and image
//   - Soft-deleted rows are excluded automatically — no WHERE deleted_at IS NULL
//   - SELECT only — use .create/.update/.delete for writes
//   - Load the "zite:sql" skill for full SQL reference (formulas, lookups, etc.)
//
// Link tables for zite.sql() JOINs (use these exact names):
//   "ChannelsMessages" — columns: "channelsId", "messagesId" (joins "Channels" and "Messages")
import { createTableClient, createSqlClient, createAuthClient } from 'zitejs/runtime';

/** An attachment as returned when reading a record. */
export type ZiteAttachment = {
  /** Original filename as uploaded. */
  filename: string;
  /** Display name — may differ from `filename`. */
  originalName: string;
  /** File size in bytes. */
  size: number;
  mimeType: string;
  /** Publicly accessible URL. */
  url: string;
  /** ISO timestamp of the upload. */
  uploadedAt: string;
  metadata?: Record<string, unknown>;
};

/** What you may write to an attachments field: a URL, a URL with a name, or an attachment you read earlier. */
export type ZiteAttachmentInput =
  | string
  | { url: string; filename?: string }
  | ZiteAttachment;

/** A record in the "Channels" table, as it is read back. */
export type ChannelsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  type?: "Public" | "Private" | string;
  icon?: string;
  /** "Sort Order". 1 decimal places, format: local (e.g. 1,000,000.50) */
  sortOrder?: number;
  /** Links to messages ("Messages"). "Messages" */
  messages?: string | string[];
  readOnly?: boolean;
  createdBy?: string | string[];
  dmParticipants?: string;
};

/** What you may write when creating or updating a record in the "Channels" table. */
export type ChannelsRecordInput = {
  name: string | null;
  type: "Public" | "Private" | string | null;
  icon: string | null;
  sortOrder: string | number | null;
  messages: string | string[] | null;
  readOnly: string | boolean | null;
  createdBy: string | string[] | null;
  dmParticipants: string | null;
};

/** A record in the "Messages" table, as it is read back. */
export type MessagesRecordType = {
  id: string;
  /** Primary field. "Content" */
  content?: string;
  /** Links to channels ("Channels"). "Channel" */
  channel?: string | string[];
  author?: string | string[];
  replyToId?: string;
  replyPreview?: string;
  replyAuthorName?: string;
  /** Read-only. "Sent At". Auto-set when record was created (ISO 8601) */
  sentAt?: string;
  imageUrl?: string;
};

/** What you may write when creating or updating a record in the "Messages" table. */
export type MessagesRecordInput = {
  content: string | null;
  channel: string | string[] | null;
  author: string | string[] | null;
  replyToId: string | null;
  replyPreview: string | null;
  replyAuthorName: string | null;
  imageUrl: string | null;
};

/** A record in the "Typing Indicators" table, as it is read back. */
export type TypingIndicatorsRecordType = {
  id: string;
  /** Primary field. "Channel Id" */
  channelId?: string;
  typer?: string | string[];
  /** "Last Typed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastTypedAt?: string;
};

/** What you may write when creating or updating a record in the "Typing Indicators" table. */
export type TypingIndicatorsRecordInput = {
  channelId: string | null;
  typer: string | string[] | null;
  lastTypedAt: string | Date | null;
};

export interface NotificationLink {
  path?: string;
  params?: Record<string, string>;
}

export interface NotificationsCreateParams {
  recipients: string[];
  title: string;
  body?: string;
  link?: NotificationLink;
  path?: string;
  params?: Record<string, string>;
  payload?: Record<string, unknown>;
  idempotencyKey?: string;
}

export type NotificationsCreateResult =
  | { created: number }
  | { created: 0; preview: true; wouldCreate: number };

export interface ZiteAuthUser {
  id: string;
  name: string;
  email: string;
  firstName?: string;
  lastName?: string;
  image: string | null;
}

export const zite = {
  channels: createTableClient<ChannelsRecordType, ChannelsRecordInput>('Channels'), // "Channels"
  messages: createTableClient<MessagesRecordType, MessagesRecordInput>('Messages'), // "Messages"
  typingIndicators: createTableClient<TypingIndicatorsRecordType, TypingIndicatorsRecordInput>('TypingIndicators'), // "Typing Indicators"
  sql: createSqlClient(),
  auth: createAuthClient<ZiteAuthUser>(),
};
